name: fourier-diffusion
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - pytorch=2.2
  - torchvision
  - pip
  - pip:
      - lightning==2.2.0
      - deepdiff
      - pillow
      - einops
      - matplotlib
